#pragma once

#define BBKEY_HOMEPOS TEXT("HomePos")
#define BBKEY_PATROLPOS TEXT("PatrolPos")
#define BBKEY_TARGET TEXT("Target")
#define BBKEY_ATTACKPOS TEXT("AttackPos")
#define BBKEY_MESHTARGETZOFFSET TEXT("MeshTargetZOffset")
#define BBKEY_BOSSTATE TEXT("BossState")
#define BBKEY_TARGETPOS TEXT("TargetPos")
#define BBKEY_CURRENTPHASE TEXT("CurrentPhase")
#define BBKEY_STARTPOS TEXT("StartPos")
#define BBKEY_BUSEMAPPATTERN TEXT("bUseMapPattern")
#define BBKEY_USEROTATEBEFOREATTACK TEXT("bUseRotateBeforeAttack")
#define BBKEY_TARGETYAWOFFSET TEXT("TargetYawOffset")
#define BBKEY_TARGETMESHPITCH TEXT("TargetMeshPitch")